Task2
MrPrograMax/golang-course-2024 pull request #11
Opened 2024-04-08 13:43 UTC by MrPrograMax

2024-04-09 16:47 UTC, kirreal requested changes
По идее, должно быть 3 уровня: 
1. клиент, который запрашивает комиксы и возвращает массив структур, проверяя ошибки rest'a.
2. Уровень бд с методами - сохрани комикс и отдай коммиксы
3. Уровень сервиса, который должен быть в xkcd в котором все эти операции должны объединяться.

2024-04-09 16:47 UTC, kirreal commented on pkg/xkcd/client.go
> +	c := http.Client{Timeout: time.Duration(1) * time.Second}
Тут можно просто 1 * time.Second
Также желательно такие параметры выносить в константы

2024-04-09 16:47 UTC, kirreal commented on pkg/xkcd/client.go
> +	comics := make(map[string]database.ComicDetails, 0)
Тут 0 не обязателен

2024-04-09 16:47 UTC, kirreal commented on pkg/xkcd/client.go
> +		var comic database.ComicData
А что если в результате пришел не комикс, а ошибка? Например, response code 500 или 404?

2024-04-09 16:47 UTC, kirreal commented on pkg/xkcd/client.go
> +func BuildClient() {
Очень странная функция, которая должна быть клиентом для получения комиксов, а она и конфиг загружает и шлет запрос и тут же в базу сохраняет и печатает

2024-04-09 16:47 UTC, kirreal commented on pkg/database/Comic.go
> +type ComicData struct {
Тут только модель данных, причем, ComicData - это не модель базы данных, а модель rest, она, скорее всего должна быть объявлена в xkcd клиенте и только он должен о ней знать

2024-04-09 16:47 UTC, kirreal commented on cmd/xkcd/main.go
> +	xkcd.BuildClient()
Слишком уж минималистичный main. Тут по идее, должна быть загрузка конфига, обработка аргументов cmd line, и установка зависимостей

2024-04-09 17:19 UTC, MrPrograMax commented
Извиняюсь, что в последний день. Неделя очень забитая была, исправлю в ближайшее время!

2024-04-10 19:27 UTC, MrPrograMax commented
Переделал методы. Не до конца понял на счет сервиса, который собирает все функции. Я правильно думаю, что в main должна быть какая то такая структура:

`
client := xkcd.NewClient(config)
database := database.NewDataBase(client)
services := service.NewService(database)
`
И внутри NewSomething там интерфейсы собираются с методами

2024-04-11 15:25 UTC, kirreal approved these changes

2024-04-11 15:55 UTC, merged